### ISSUE TITLE
Error: memoize in react native export field type into tsconfig

### ISSUE THREAD

**Issue by NamVinh** [sindresorhus/memoize#100]
This is my tsconfig.json. Can you help me fix it ?

{
"$schema": "https://json.schemastore.org/tsconfig",
"display": "React Native",
"extends": "./base.json",
"compilerOptions": {
"target": "esnext",
"module": "es2015",
"moduleResolution": "bundler",
"types": ["react-native"],
"lib": [
"es2019",
"es2020.bigint",
"es2020.date",
"es2020.number",
"es2020.promise",
"es2020.string",
"es2020.symbol.wellknown",
"es2021.promise",
"es2021.string",
"es2021.weakref",
"es2022.array",
"es2022.object",
"es2022.string"
],
"allowJs": true,
"jsx": "react-native",
"noEmit": true,
"isolatedModules": true,
"strict": true,
"customConditions": ["react-native"],
"allowImportingTsExtensions": true,
"allowArbitraryExtensions": true,
"resolveJsonModule": true,
"resolvePackageJsonImports": false,
"allowSyntheticDefaultImports": true,
"esModuleInterop": true,
"skipLibCheck": true,
"forceConsistentCasingInFileNames": false
},
"exclude": ["node_modules", "babel.config.js", "metro.config.js", "jest.config.js"]
}

**Comment by fregante** [comment]
Stop
