### ISSUE TITLE
Cannot find module 'memoize' or its corresponding type declarations.

### ISSUE THREAD

**Issue by shemzz** [sindresorhus/memoize#101]
Having installed memoize v10 using pnpm,  I get this message on importing memoize

`Cannot find module 'memoize' or its corresponding type declarations.
  There are types at '**/node_modules/memoize/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.`

Currently on node20 with experimentalDecorators set to true. This should work out of the box, right?

**Comment by sindresorhus** [comment]
The error message says it all.
