### ISSUE TITLE
Typescript unable to find typings

### ISSUE THREAD

**Issue by mattfysh** [sindresorhus/memoize#95]
Hi there, thanks for your great npm packages!

Inspecting the package.json from the recent v10 and it appears the layout has changed. Did you intend to move `index.d.ts` under the `exports.types` key? previously it was located in the root `types` field

I'm using the latest version of typescript and it appears that it fails to find the correct types with the new layout

Cheers!

**Comment by mattfysh** [comment]
Apologies, this was a tsconfig issue

**Comment by perry-mitchell** [comment]
@mattfysh Would you mind sharing what the issue was?

**Comment by mattfysh** [comment]
@perry-mitchell it was one of these, hope it works for you!

```
"module": "esnext",
"moduleResolution": "bundler",
```

**Comment by jakub-tucek** [comment]
I just used this hack to avoid changing tsconfig. Would need some tweaks if you plan to use other exported types though:

_memoize.d.ts_
```ts
declare module 'memoize' {
	import * as m from 'memoize/dist/index';
	export default m.default;
}
```
