### ISSUE TITLE
Import fails, no types

### ISSUE THREAD

**Issue by perry-mitchell** [sindresorhus/memoize#96]
Hello!

Was using `mem` and updated to `memoize`, but am getting the following compilation error:

```
error TS2307: Cannot find module 'memoize' or its corresponding type declarations.

3 import memoize from "memoize";
```

![image](https://github.com/sindresorhus/memoize/assets/3869469/384b62cb-e9fe-436c-a440-806dfe06fb7b)

My project has been ESM for a long time, with many other ESM-only dependencies working just fine. I'm on the latest Typescript version, Node 20.

My tsconfig in case it helps:

```json
{
    "compilerOptions": {
        "allowJs": false,
        "declaration": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "module": "ES2020",
        "moduleResolution": "node",
        "outDir": "../../dist/dispatcher",
        "strictNullChecks": true,
        "target": "ES2020",
        "types": ["node", "express"]
    },
    "include": [
        "./source/**/*",
        "../shared/**/*"
    ]
}

```

**Comment by fregante** [comment]
I think you need to use moduleResolution: bundler or node16

**Comment by paul-vd** [comment]
Why not include the types?
